name: Lint files

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-php:
    name: Lint PHP files
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.0

      - name: Set up PHP
        uses: shivammathur/setup-php@2.26.0
        with:
          coverage: none
          php-version: "8.2"
        env:
          fail-fast: 'true'

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@2.2.0

      - name: Lint files
        run: ./vendor/bin/phpcs . --warning-severity=8
