name: PHPUnit

on:
    pull_request:
      branches:
        - '*'
    workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@2.2.0

      - name: Run PHPUnit
        run: vendor/bin/phpunit
