name: PHPUnit

on:
    pull_request:
      branches:
        - '*'
    workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run PHPUnit
        run: vendor/bin/phpunit
