<?php

declare( strict_types=1 );

use PHPUnit\Framework\TestCase;

require_once __DIR__ . '/../../lib/github-changelog.php';

define( 'PR_CHANGELOG_START_MARKER', '<h2>Changelog Description' );
define( 'PR_CHANGELOG_END_MARKER', '<h2>' );
define( 'LINK_TO_PR', false );

class GitHub_Changelog_Test extends TestCase {
	public function test_get_changelog_html(): void {
		$pr = array();

		$pr['body'] = '# Description
		
Changes were made

## A different section

Content here

## Changelog Description

### This is my changelog title

<!-- An HTML Comment -->

Things we did:

* Fixed a bug
* Fixed another bug

## And another section that isn\'t a changelog

Foo Bar!';

		$changelog = get_changelog_html( $pr );

		$this->assertEquals(
			'<h3>This is my changelog title</h3>
<p>Things we did:</p>
<ul>
<li>Fixed a bug</li>
<li>Fixed another bug</li>
</ul>',
			$changelog 
		);
	}

	public function test_parse_changelog_html_with_autogenerated_date_title(): void {
		$pr = array();

		$html = '<h3>Fixed</h3>
<ul>
<li>Fixed a bug</li>
<li>Fixed another bug</li>
</ul>';

		$parsed = parse_changelog_html( $html );

		$this->assertEquals( gmdate( 'o-m-d H:i' ), $parsed['title'] );
		$this->assertEquals(
			'<h3>Fixed</h3>
<ul>
<li>Fixed a bug</li>
<li>Fixed another bug</li>
</ul>',
			$parsed['content'] 
		);
	}

	public function test_parse_changelog_html_with_no_title_found(): void {
		$pr = array();

		$html = 'this is the html of my changelog, it does not contain a title so it needs to autogenerate';

		$parsed = parse_changelog_html( $html );

		$this->assertEquals( gmdate( 'o-m-d H:i' ), $parsed['title'] );
		$this->assertEquals( $html, $parsed['content'] );
	}
}
